name: CI

on:
  pull_request:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: --deny warnings

jobs:
  style:
    name: Check basic style
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: LukasKalbertodt/check-basic-style@v0.1

  check:
    name: 'Build & test'
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - name: Restore Cache
      uses: Swatinem/rust-cache@v2
    - name: Build
      run: cargo build
    - name: Run tests with file formats
      run: cargo test --features=toml,yaml,json5
    - name: Run tests
      run: cargo test
